# Generated by Django 5.0 on 2023-12-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videoaula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('nivel', models.CharField(choices=[('Nivel_Jr', 'Nível Jr'), ('Nivel_1', 'Nível 1'), ('Nivel_2', 'Nível 2'), ('Nivel_S', 'Nível Sênior')], max_length=20)),
                ('fase', models.CharField(choices=[('Fase_1', 'Fase 1'), ('Fase_2', 'Fase 2'), ('Fase_3', 'Fase 3')], max_length=20)),
                ('link_youtube', models.URLField()),
                ('arquivo_codigo', models.FileField(upload_to='arquivos_codigo/')),
                ('thumb', models.ImageField(upload_to='thumbs/')),
            ],
        ),
    ]
