# Generated by Django 5.0 on 2023-12-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videoaulas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoaula",
            name="ano",
            field=models.CharField(
                choices=[("ANO2020", "2020"), ("ANO2019", "2019")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="videoaula",
            name="thumb",
            field=models.ImageField(null=True, upload_to="thumbs/"),
        ),
    ]
